version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "127.0.0.1:7233"
  activities:
    num_workers: 4

service:
  interceptors:
    command: "./rr serve -c ./src/Interceptors/.rr.yaml"

logs:
  level: info
  mode: development

otel:
  insecure: true
  compress: false
  client: http
  exporter: otlp
  service_name: rr-temporal-samples
  service_version: 1.0.0
  endpoint: collector:4318
