version: "3.0"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4

logs:
  level: debug
  mode: development

otel:
  insecure: true
  compress: false
  client: http
  exporter: otlp
  service_name: rr-temporal-samples
  service_version: 1.0.0
  endpoint: collector:4318
